export OST_GETH_VALUE_RPC_PROVIDER='http://localhost:8545'
export OST_GETH_VALUE_WS_PROVIDER='ws://localhost:18545'

export OST_GETH_UTILITY_RPC_PROVIDER='http://localhost:9546'
export OST_GETH_UTILITY_WS_PROVIDER='ws://localhost:19546'

export OST_VALUE_CHAIN_ID=2001
export OST_UTILITY_CHAIN_ID=2000

export OST_FOUNDATION_ADDR=''
export OST_FOUNDATION_PASSPHRASE='testtest'

export OST_DEPLOYER_ADDR=''
export OST_DEPLOYER_PASSPHRASE='testtest'

export OST_UTILITY_CHAIN_OWNER_ADDR='0x3300b94e021b63b4cf6a55e568c295b86e578fa2'
export OST_UTILITY_REGISTRAR_CONTRACT_ADDR=''
export OST_OPENSTUTILITY_CONTRACT_ADDR=''
export OST_OPENSTUTILITY_ST_PRIME_UUID=''

export OST_VALUE_REGISTRAR_ADDR=''
export OST_VALUE_REGISTRAR_PASSPHRASE='testtest'

export OST_UTILITY_REGISTRAR_ADDR=''
export OST_UTILITY_REGISTRAR_PASSPHRASE='testtest'

export OST_SIMPLE_TOKEN_CONTRACT_ADDR=''
export OST_OPENSTVALUE_CONTRACT_ADDR=''
export OST_STPRIME_CONTRACT_ADDR=''
export OST_VALUE_CORE_CONTRACT_ADDR=''
export OST_VALUE_REGISTRAR_CONTRACT_ADDR=''

export OST_STAKING_CONTRACT_ADDR=''
export OST_UTILITY_TOKEN_CONTRACT_ADDR=''

export OST_UTILITY_STPRIME_TOTAL_SUPPLY=800000000

export OST_FOUNDATION_ADDR='0x994e0d1fb88166edcce9ca445b711311c707c0cb'
export OST_REGISTRAR_ADDR='0x3bcc730dff0c79d993d101b817905fc52cb9fe43'

export OST_DEPLOYER_ADDR='0x1ec9b46c8d594ded82ead4b6c644b98f6d8e77f3'