export OST_GETH_VALUE_RPC_PROVIDER='http://localhost:8545'
export OST_GETH_VALUE_WS_PROVIDER='ws://localhost:18545'

export OST_GETH_UTILITY_RPC_PROVIDER='http://localhost:9546'
export OST_GETH_UTILITY_WS_PROVIDER='ws://localhost:19546'

export OST_VALUE_CHAIN_ID=2001
export OST_UTILITY_CHAIN_ID=2000

export OST_FOUNDATION_ADDR=''
export OST_FOUNDATION_PASSPHRASE='testtest'

export OST_VALUE_DEPLOYER_ADDR=''
export OST_VALUE_DEPLOYER_PASSPHRASE='testtest'

export OST_UTILITY_DEPLOYER_ADDR=''
export OST_UTILITY_DEPLOYER_PASSPHRASE='testtest'

export OST_VALUE_OPS_ADDR=''
export OST_VALUE_OPS_PASSPHRASE='testtest'

export OST_UTILITY_CHAIN_OWNER_ADDR=''
export OST_UTILITY_REGISTRAR_CONTRACT_ADDR=''
export OST_OPENSTUTILITY_CONTRACT_ADDR=''
export OST_OPENSTUTILITY_ST_PRIME_UUID=''

export OST_VALUE_REGISTRAR_ADDR=''
export OST_VALUE_REGISTRAR_PASSPHRASE='testtest'

export OST_UTILITY_REGISTRAR_ADDR=''
export OST_UTILITY_REGISTRAR_PASSPHRASE='testtest'

export OST_MANAGED_KEY_PASSPHRASE='testtest'
export OST_UTILITY_CHAIN_OWNER_PASSPHRASE='testtest'

export OST_SIMPLE_TOKEN_CONTRACT_ADDR=''
export OST_OPENSTVALUE_CONTRACT_ADDR=''
export OST_STPRIME_CONTRACT_ADDR=''
export OST_VALUE_CORE_CONTRACT_ADDR=''
export OST_VALUE_REGISTRAR_CONTRACT_ADDR=''

export OST_UTILITY_TOKEN_CONTRACT_ADDR=''

export OST_UTILITY_STPRIME_TOTAL_SUPPLY=800000000